defaults:
  run:
    shell: bash

on:
  workflow_dispatch:

name: vs-placebo build

jobs:
  build_vs_placebo:
    name: Building vs-placebo
    runs-on: ubuntu-latest
    env:
      CURL_RETRIES: "--connect-timeout 60 --retry 999 --retry-delay 5 --retry-all-errors"
    container:
      image: docker://archlinux:base-devel

    steps:

      - name: Get current date and random hash
        run: |
          echo "short_date=$(date "+%Y%m%d")" >> $GITHUB_ENV
          echo "random_hash=$(echo $RANDOM | md5sum | head -c 20)" >> $GITHUB_ENV

      - name: Installing dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed jq openssh git gyp mercurial subversion ninja cmake ragel yasm nasm asciidoc enca gperf unzip p7zip gcc-multilib clang python-pip curl lib32-glib2 wget
          pip3 install rst2pdf mako meson
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v3
        with:
          ref: vs-placebo-winbuild

      - name: Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            src_packages
            build64
          key: ${{ runner.os }}-build-mycache-${{ secrets.CACHE_VERSION }}-vsplacebo

      - name: Cache info
        run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"

      - name: Downloading source
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DALWAYS_REMOVE_BUILDFILES=ON -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -Bbuild64 -H.
          ninja -C build64 download || true

      - name: Building toolchain
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        id: build_toolchain
        continue-on-error: true
        run: |
          if [[ ! "$(ls -A build64/install/bin)" ]]; then ninja -C build64 gcc; fi

      - name: Building vs-placebo
        id: build_vs_placebo
        if: ${{ steps.cache.outputs.cache-hit == 'true' || steps.build_toolchain.outcome == 'success' }}
        continue-on-error: true
        run: |
          ninja -C build64 vs-placebo

      - name: Packaging vs-placebo
        id: packaging_vs_placebo
        if: ${{ steps.build_vs_placebo.outcome == 'success' }}
        continue-on-error: true
        run: |
          mkdir -p release
          mv build64/install/x86_64-w64-mingw32/lib64/vapoursynth/libvs_placebo.dll .
          7z a ./release/libvs_placebo.zip libvs_placebo.dll
          rm -f ./libvs_placebo.dll

      - name: Uploading release
        id: uploading_release
        if: ${{ steps.packaging_vs_placebo.outcome == 'success' }}
        uses: actions/upload-artifact@v3
        with:
          name: vs-placebo
          path: release

      - name: Collecting logs
        id: collect_logs
        run: |
          mkdir -p build64_logs
          cp -fr $(find build64 -type f -iname "*-*.log") build64_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z build*logs

      - name: Uploading logs
        id: upload_logs
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs.7z
          retention-days: 1

      - name: Cleaning build directory
        id: delete_build_dir
        run: |
          ninja -C build64 libplacebo-fullclean
          ninja -C build64 vs-placebo-fullclean
          du -sh build64 src_packages /var/cache/pacman/pkg || true
